### ISSUE TITLE
登录屏幕出现。看起来服务器根本就没有启动。- The login screen shows. Seems like msojocs-server is not up.

### ISSUE THREAD

**Issue by Lyf888lyf** [sipsuru/fiddler-everywhere-patch-automated#5]
在登录界面不停反复，进不去。
偶尔进去之后，重启又需要登录。

**Comment by sipsuru** [comment]
> [!NOTE]
> 由AI翻译 (Translated with AI)

你能提供一些截图吗？

你能指出你触发actions script的repository分支吗？这样我可以下载构建产物并进行测试。

**Comment by sipsuru** [comment]
实际上，如果补丁成功应用并且服务器启动，你将无法看到登录屏幕。看起来像是与 #7 类似的错误。

**Comment by sipsuru** [comment]
Well, the issue is not reproducable.
And you are not giving further information too;

You may re-open once you're ready.

**Comment by sipsuru** [comment]
You should check if the port `5678` is free, if not you need to change port from, main.js and main.XXXXXXXXX.js manually.
